spring.application.name=MotoMarkt

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/demo

spring.datasource.username=demo

spring.datasource.password=demo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true

myapp.jwtSecret=c839101a9b9b97ae14daae03fdebb916d0e86ec2d0c574c62855bf19c1d6e814
myapp.jwtExpirationMs=1000000